# docker/Dockerfile.api
FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY db/ ./db/
COPY data/ ./data/

RUN mkdir -p logs

CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
